const data = {
  cards: [
    {
      id: 1,
      name: 'Blue-Eyes White Dragon',
      typeId: 1,
      attributeId: 1,
      atk: 3000,
      def: 2500,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/89631139.jpg',
      description: 'This legendary dragon is a powerful engine of destruction, Virtually invencible, very few have faced this awesome creature and lived to tell the tale.',
    },
    {
      id: 2,
      name: 'Dark Magician',
      typeId: 2,
      attributeId: 2,
      atk: 2500,
      def: 2100,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/46986414.jpg',
      description: 'The ultimate wizard in terms of attack and defense',
    },
    {
      id: 3,
      name: 'Arianna the Labrynth Servant',
      typeId: 3,
      attributeId: 2,
      atk: 1600,
      def: 2100,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/1225009.jpg',
      description: 'If this card is Normal or Special Summoned: You can add 1 "Labrynth" card from your Deck to your hand, except "Arianna the Labrynth Servant". If another monster(s) leaves the field by your Normal Trap effect (except during the Damage Step), You can draw 1 card, then you can apply this effect. ⚫️ From your hand, either Special Summon 1 Fiend monster, or Set 1 Spell/Trap. You can only use 1 "Aryanna the Labrynth Servant" effect per turn, and only once that turn.',
    },
    {
      id: 4,
      name: 'Red-Eyes Black Dragon',
      typeId: 1,
      attributeId: 2,
      atk: 2400,
      def: 2000,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/74677422.jpg',
      description: 'A ferocious dragon with a deadly attack.',
    },
    {
      id: 5,
      name: 'D.D. Crow',
      typeId: 4,
      attributeId: 2,
      atk: 100,
      def: 100,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/24508238.jpg',
      description: '(Quick Effect): You can discard this card to the GY, then target 1 card in your opponent"s GY: banish that target.',
    },
    {
      id: 6,
      name: 'Abaki',
      typeId: 3,
      attributeId: 3,
      atk: 1700,
      def: 1100,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/12694768.jpg',
      description: 'When this card is destroyed and sent to the Graveyard by battle, both players take 500 damage.',
    },
    {
      id: 7,
      name: 'Absolute Crusader',
      typeId: 5,
      attributeId: 4,
      atk: 1700,
      def: 1100,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/70832512.jpg',
      description: 'If a Level 5 or higher monster(s) is Special Summoned: Tribute this face-up card; destroy that Level 5 or higher monster(s).',
    },
    {
      id: 8,
      name: 'Eka the Flame Buddy',
      typeId: 5,
      attributeId: 3,
      atk: 1500,
      def: 200,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/35283277.jpg',
      description: 'If this card is Normal or Special Summoned: You can target 1 face-up Monster Card in either player"s Spell or Trap Zone: Special Summon it to your field. You can target 1 other face-up monster you control; equip that face-up monster to this card as an Equip Spell that gives it 500 ATK. You can only use each effect of "Eka the Flame Buddy" once per turn.',
    },
    {
      id: 9,
      name: 'Enlightenment Paladin',
      typeId: 2,
      attributeId: 2,
      atk: 2500,
      def: 2000,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/59123194.jpg',
      description: '1 Tuner + 1 or more non-Tuner monsters. If this card is Synchro Summoned using a "Magician" Pendulum Monster as Material: You can target 1 Spell Card in your Graveyard: add it to your hand. Tou can only use this effect of "Enlightenment Paladin" once per turn. When this card destroys an opponent"s monster by battle: You can inflict damage to your opponents equal to that monster"s original ATK.',
    },
    {
      id: 10,
      name: 'Dragon Queen of Tragic Endings',
      typeId: 1,
      attributeId: 2,
      atk: 1900,
      def: 2600,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/80513550.jpg',
      description: 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned by controlling 3 or more face-up Continuous Spell Cards. When this attacking card inflicts Battle Damage to your opponent, your opponent selects and sends 1 card from their hand to the Graveyard, and you draw 1 card. During your Standby Phase, if this card is in your Graveyard and was sent there from the field, you can send 1 face-up Continuous Spell Card you control to the Graveyard to Special Summon this card from the Graveyard.',
    },
    {
      id: 11,
      name: 'Monster Reborn',
      typeId: 6,
      attributeId: 5,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/83764719.jpg',
      description: 'Target 1 monster in either GY; Special Summon it.',
    },
    {
      id: 12,
      name: 'Illusion Magic',
      typeId: 6,
      attributeId: 5,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/73616671.jpg',
      description: 'Tribute 1 Spellcaster monster; add up to 2 copies of "Dark Magician" from your Deck and/or GY to your hand. You can only activate 1 "Illusion Magic" per turn.',
    },
    {
      id: 13,
      name: 'Saber Vault',
      typeId: 6,
      attributeId: 5,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/73787254.jpg',
      description: 'Each face-up "X-Saber" monster on the field gains 100 ATK x its Level, and loses 100 DEF x its Level.',
    },
    {
      id: 14,
      name: 'Invocation',
      typeId: 6,
      attributeId: 5,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/74063034.jpg',
      description: `Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand as Fusion Material. If Summoning an "Invoked" Fusion Monster this way, you can also banish monsters from your field and/or either player's GY as Fusion Material. If this card is in your GY: You can target 1 of your banished "Aleister the Invoker"; shuffle this card into the Deck, and if you do, add that card to your hand. You can only use this effect of "Invocation" once per turn.`
    },
    {
      id: 15,
      name: 'Blue-Eyes Ultimate Dragon',
      typeId: 7,
      attributeId: 1,
      atk: 4500,
      def: 3800,
      img: 'https://ygoprodeck.com/cdn-cgi/image/format=auto,width=313/https://images.ygoprodeck.com/images/cards/23995346.jpg',
      description: '"Blue-Eyes White Dragon" + "Blue-Eyes White Dragon" + "Blue-Eyes White Dragon"',
    },
    // {
    //   id: 16,
    //   name: 'Xupinhei',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Xupinhei.jpeg',
    //   description: '',
    // },
    // {
    //   id: 17,
    //   name: 'Wes Sparrow - O Programador da Luz',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Wes-Sparrow-O-Programador-da-Luz.jpg',
    //   description: '',
    // },
    // {
    //   id: 18,
    //   name: 'Okami Bafo de Dragão',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Okami-Bafo-de-Dragão.jpg',
    //   description: '',
    // },
    // {
    //   id: 19,
    //   name: 'A Pega',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/A-pega.png',
    //   description: 'Uma bela carta para enfeitar o seu deck. Supostamente é apenas decorativa, supostamente.',
    // },
    // {
    //   id: 20,
    //   name: 'Black Eyes Brown Turtle',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Black-Eyes-Brown-Turtle.png',
    //   description: 'When this monster is summoned, all monsters must say aaaaaaaah in a certain way. When defeated, all monsters must say AI.',
    // },
    // {
    //   id: 21,
    //   name: 'Cadeia',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Cadeia.jpeg',
    //   description: '',
    // },
    // {
    //   id: 22,
    //   name: 'Conforto Emocional',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Conforto-Emocional.jpg',
    //   description: 'Ao olhar no fundo dos olhos, permite a você codar por mais 5 horas ininterruptas.',
    // },
    // {
    //   id: 23,
    //   name: 'Developer',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Developer.png',
    //   description: '',
    // },
    // {
    //   id: 24,
    //   name: 'Duda - Dragão Lendário',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Duda-Dragão-Lendário.png',
    //   description: '',
    // },
    // {
    //   id: 25,
    //   name: 'Emerson - O Pinguim Lendário',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Emerson-O-Pinguim-Bárbaro.jpg',
    //   description: '',
    // },
    // {
    //   id: 26,
    //   name: 'Henrique - Criatura Estranha',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Henrique-Criatura-Estranha.png',
    //   description: '',
    // },
    // {
    //   id: 27,
    //   name: 'Hulk do Goiás',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Hulk-do-Goiás.png',
    //   description: '',
    // },
    // {
    //   id: 28,
    //   name: 'Lucas - Guardião do Portão',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Lucas-Guardião-do-Portão.png',
    //   description: '',
    // },
    // {
    //   id: 29,
    //   name: 'Marcos Chat GPT-7',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Marcos-Chat-Gpt-7.jpeg',
    //   description: '',
    // },
    // {
    //   id: 30,
    //   name: 'Gus - Dragão de Olhos de Águia',
    //   typeId: 8,
    //   attributeId: 6,
    //   img: './trybeCards/Gus-Dragão-de-Olhos-de-Águia.png',
    //   description: 'Uma carta para todas governar, Uma carta para encontrá-los. Uma carta para todos trazer e na escuridão aprisioná-los. Aquele que possui a pega. Tenha cuidado, sempre ande pela sombra e beba suco de cajú gelado pelo menos 2x por semana.',
    // },
    // {
    //   id: 31,
    //   name: '10 Mandamentos de Hofs',
    //   typeId: 8,
    //   attributeId: 6,
    //   img: './trybeCards/10-Mandamentos-de-Hofs.png',
    //   description: 'Você aprende um mandamento de HoFs por turno enquanto essa carta estiver em campo. Bônus: Também aprende a abrir o mar. 🌊',
    // },
    // {
    //   id: 32,
    //   name: 'Isa - Guepardo Good Vibes',
    //   typeId: 8,
    //   attributeId: 6,
    //   img: './trybeCards/Isa-Guepardo-Good-Vibes.png',
    //   description: 'Um foguete? Um avião? Um caminhão? Alguém anotou a placa? Enfrente a "fúria" do guepardo good vibes com um cházinho quente e um par de pantufas, pois tudo o que esta criatura quer é paz.',
    // },
    // {
    //   id: 33,
    //   name: 'Luquinha Tomando Uma',
    //   typeId: 8,
    //   attributeId: 6,
    //   img: './trybeCards/Luquinha-Tomando-Uma.png',
    //   description: 'Quando esta carta entre em campo, todas as cartas tem que tomar uma. 🍺',
    // },
    // {
    //   id: 34,
    //   name: 'Nat - This is The Way',
    //   typeId: 8,
    //   attributeId: 6,
    //   img: './trybeCards/Nat-This-Is-The-Way.png',
    //   description: 'Use essa carta para descobrir a força que existe em você! ⭐️⭐️⭐️⭐️⭐️',
    // },
    // {
    //   id: 35,
    //   name: 'O Oráculo Baiano',
    //   typeId: 8,
    //   attributeId: 6,
    //   img: './trybeCards/O-Oráculo-Baiano.jpeg',
    //   description: 'Quando ativada, Zezé aparece para te dar uma dica de HoFs. Uso combinado: No Slack, +500 de ataque, na Mentoria, +500 de defesa.',
    // },
    // {
    //   id: 36,
    //   name: 'Pausa Para o Autocuidado',
    //   typeId: 8,
    //   attributeId: 6,
    //   img: './trybeCards/Pausa-Para-o-Autocuidado.png',
    //   description: 'Quando recebe essa carta é um lembrete de que pause o estudo/trabalho por 20 minutos. Faça algo que goste e precise nesse tempo (cuidar das plantas, abrace os pets 😸🐶, tirar um cochilo, etc.). Escute o seu corpo e te dirá o que precisa fazer.',
    // },
    // {
    //   id: 37,
    //   name: 'Surfista Platinado',
    //   typeId: 8,
    //   attributeId: 6,
    //   img: './trybeCards/Surfista-Platinado.jpeg',
    //   description: 'Assim que essa carta entra em campo, todas as suas dúvidas são resolvidas ou é necessário realizar um pix a cada turno.',
    // },
    // {
    //   id: 38,
    //   name: 'Trybe-Fi',
    //   typeId: 8,
    //   attributeId: 6,
    //   img: './trybeCards/Trybe-Fi.jpeg',
    //   description: 'Use essa playlist para relaxar sempre que sentir cansaço. Fique sem jogar nessa rodada, na próxima você ganha +1000 de lógica.',
    // },
    // {
    //   id: 39,
    //   name: 'Duolingo Card',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Duolingo-Card.png',
    //   description: '',
    // },
    // {
    //   id: 40,
    //   name: 'Xabalu da Midnight',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/XabaludaMidnight.jpeg',
    //   description: '',
    // },
    // {
    //   id: 41,
    //   name: 'Polimerização',
    //   typeId: 7,
    //   attributeId: 6,
    //   img: './trybeCards/Polimerizacao.jpg',
    //   description: 'Utilize essa carta para fundir duas tartatugas e obter uma ainda mais forte! Esta carta também é ativada quando identifica algum erro em seu código... "Aaaahhhh!!"',
    // },
    // {
    //   id: 42,
    //   name: 'Iguim - Príncipe do Commitão Bomba',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Iguim-Principe-do-Commitao-Bomba.png',
    //   description: '',
    // },
    // {
    //   id: 43,
    //   name: 'Sangue de Maria Bonita',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Sangue-de-Maria-Bonita.png',
    //   description: '',
    // },
    // {
    //   id: 44,
    //   name: 'Carol - Aprendendo a Relaxar',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Carol-Aprendendo-a-Relaxar.png',
    //   description: '',
    // },
    // {
    //   id: 45,
    //   name: 'Altin Anka KuSu - Fênix Dourada',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Altin-Anka-Kusu-Fenix-Dourada.png',
    //   description: '',
    // },
    // {
    //   id: 46,
    //   name: 'No More Test',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/No-More-Test.jpeg',
    //   description: '',
    // },
    // {
    //   id: 47,
    //   name: 'Pinguça Lendária',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Pinguca-Lendaria.png',
    //   description: '',
    // },
    // {
    //   id: 48,
    //   name: 'Armadilha do Lint',
    //   typeId: 9,
    //   attributeId: 6,
    //   img: './trybeCards/Armadilha-do-Lint.png',
    //   description: '',
    // },
    // {
    //   id: 49,
    //   name: 'Momento de Abraçar Animais',
    //   typeId: 8,
    //   attributeId: 6,
    //   img: './trybeCards/Momento-de-Abracar-Animais.png',
    //   description: 'Ao receber esta carta pare tudo que estiver fazendo e dê um abraço, um cafuné e um cheirinho no seu pet ou pegue um pet de alguém emprestado para isso.',
    // },
  ],

  types: [
    {
      id: 1,
      name: 'Dragon',
    },
    {
      id: 2,
      name: 'Spellcaster',
    },
    {
      id: 3,
      name: 'Fiend',
    },
    {
      id: 4,
      name: 'Winged Beast',
    },
    {
      id: 5,
      name: 'Warrior',
    },
    {
      id: 6,
      name: 'Spell Card'
    },
    {
      id: 7,
      name: 'Fusion Monster'
    },
    {
      id: 8,
      name: 'Trybe Team'
    },
    {
      id: 9,
      name: 'Turma 31'
    },
  ],

  attributes: [
    {
      id: 1,
      name: 'Light',
    },
    {
      id: 2,
      name: 'Dark',
    },
    {
      id: 3,
      name: 'Fire',
    },
    {
      id: 4,
      name: 'Earth',
    },
    {
      id: 5,
      name: 'N/A',
    },
    {
      id: 6,
      name: 'Dev'
    }
  ],
}

module.exports = data;