module.exports = {
  clubs: [
    {
      name: 'Real Madrid',
      country: 'Espanha',
      years: [1960, 1998, 2002, 2014, 2016, 2017, 2018, 2022],
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/1200px-Real_Madrid_CF.svg.png',
    },
    {
      name: 'Milan',
      country: 'Itália',
      years: [1969, 1989, 1990, 2007],
      logo: 'https://logodetimes.com/times/associazione-calcio-milan/associazione-calcio-milan-4096.png',
    },
    {
      name: 'Bayern de Munique',
      country: 'Alemanha',
      years: [1976, 2001, 2013, 2020],
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/1200px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png',
    },
    {
      name: 'Barcelona',
      country: 'Espanha',
      years: [2009, 2011, 2015],
      logo: 'https://upload.wikimedia.org/wikipedia/pt/thumb/4/43/FCBarcelona.svg/2020px-FCBarcelona.svg.png',
    },
    {
      name: 'São Paulo',
      country: 'Brasil',
      years: [1992, 1993, 2005],
      logo: 'https://upload.wikimedia.org/wikipedia/pt/4/4b/S%C3%A3o_Paulo_Futebol_Clube.png',
    },
    {
      name: 'Inter de Milão',
      country: 'Itália',
      years: [1964, 1965, 2010],
      logo: 'https://logodownload.org/wp-content/uploads/2017/02/inter-milan-logo-1.png',
    },
    {
      name: 'Boca Juniors',
      country: 'Argentina',
      years: [1977, 2000, 2003],
      logo: 'https://logodownload.org/wp-content/uploads/2016/10/boca-juniors-logo-escudo-1-1.png',
    },
    {
      name: 'Peñarol',
      country: 'Uruguai',
      years: [1961, 1966, 1982],
      logo: 'https://logodownload.org/wp-content/uploads/2018/04/penarol-logo-escudo.png',
    },
    {
      name: 'Nacional',
      country: 'Uruguai',
      years: [1971, 1980, 1988],
      logo: 'https://logodetimes.com/times/nacional-uruguai/logo-nacional-uruguai-4096.png',
    },
    {
      name: 'Santos',
      country: 'Brasil',
      years: [1962, 1963],
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Santos_logo.svg/640px-Santos_logo.svg.png',
    },
    {
      name: 'Corinthians',
      country: 'Brasil',
      years: [2000, 2012],
      logo: 'https://logodownload.org/wp-content/uploads/2016/11/corinthians-logo-01.png',
    },
    {
      name: 'Juventus',
      country: 'Itália',
      years: [1985, 1996],
      logo: 'https://logodownload.org/wp-content/uploads/2017/02/juventus-logo.png',
    },
    {
      name: 'Independiente',
      country: 'Argentina',
      years: [1973, 1984],
      logo: 'https://logodownload.org/wp-content/uploads/2018/07/clube-independiente-logo-escudo.png',
    },
    {
      name: 'Manchester United',
      country: 'Inglaterra',
      years: [1999, 2008],
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/640px-Manchester_United_FC_crest.svg.png',
    },
    {
      name: 'Ajax',
      country: 'Holanda',
      years: [1972, 1995],
      logo: 'https://upload.wikimedia.org/wikipedia/sco/thumb/7/79/Ajax_Amsterdam.svg/1200px-Ajax_Amsterdam.svg.png',
    },
    {
      name: 'Porto',
      country: 'Portugal',
      years: [1987, 2004],
      logo: 'https://logodownload.org/wp-content/uploads/2017/03/fc-porto-logo-1.png',
    },
    {
      name: 'Atlético de Madrid',
      country: 'Espanha',
      years: [1974],
      logo: 'https://logodownload.org/wp-content/uploads/2017/02/atletico-madrid-logo-0.png',
    },
    {
      name: 'Internacional',
      country: 'Brasil',
      years: [2006],
      logo: 'https://logodetimes.com/times/internacional/logo-internacional-4096.png',
    },
    {
      name: 'Grêmio',
      country: 'Brasil',
      years: [1983],
      logo: 'https://logodownload.org/wp-content/uploads/2017/02/gremio-logo-escudo.png',
    },
    {
      name: 'Flamengo',
      country: 'Brasil',
      years: [1981],
      logo: 'https://logodownload.org/wp-content/uploads/2016/09/flamengo-logo-escudo-novo-1.png',
    },
    {
      name: 'River Plate',
      country: 'Argentina',
      years: [1986],
      logo: 'https://logodownload.org/wp-content/uploads/2015/05/river-plate-logo-6.png',
    },
    {
      name: 'Estudiantes',
      country: 'Argentina',
      years: [1968],
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Escudo_de_Estudiantes_de_La_Plata.svg/1200px-Escudo_de_Estudiantes_de_La_Plata.svg.png',
    },
    {
      name: 'Racing',
      country: 'Argentina',
      years: [1967],
      logo: 'https://logodownload.org/wp-content/uploads/2018/10/racing-logo-escudo-1.png',
    },
    {
      name: 'Vélez Sarsfield',
      country: 'Argentina',
      years: [1994],
      logo: 'https://logodetimes.com/times/velez-sarsfield/logo-velez-sarsfield-4096.png',
    },
    {
      name: 'Borussia Dortmund',
      country: 'Alemanha',
      years: [1997],
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/1200px-Borussia_Dortmund_logo.svg.png',
    },
    {
      name: 'Liverpool',
      country: 'Inglaterra',
      years: [2019],
      logo: 'https://upload.wikimedia.org/wikipedia/pt/thumb/0/0c/Liverpool_FC.svg/1200px-Liverpool_FC.svg.png',
    },
    {
      name: 'Feyenoord',
      country: 'Holanda',
      years: [1970],
      logo: 'https://logodownload.org/wp-content/uploads/2022/03/feyenoord-logo-1.png',
    },
    {
      name: 'Estrela Vermelha',
      country: 'Sérvia',
      years: [1991],
      logo: 'https://logodownload.org/wp-content/uploads/2020/03/crvena-zvezda-logo-1.png',
    },
    {
      name: 'Olímpia',
      country: 'Paraguai',
      years: [1979],
      logo: 'https://logodownload.org/wp-content/uploads/2019/04/olimpia-logo-escudo.png',
    },
    {
      name: 'Chelsea',
      country: 'Inglaterra',
      years: [2021],
      logo: 'https://upload.wikimedia.org/wikipedia/pt/thumb/c/cc/Chelsea_FC.svg/2048px-Chelsea_FC.svg.png',
    },
  ],
};
